### ISSUE TITLE
Website Revision: GUECO_KARL

### ISSUE THREAD

**Issue by Bindetta** [Bindetta/GROUP5_CASE_STUDY_GITHUB#7]
**FEEDBACK:**

- Pixelated picture on the back
- Pick complement colors as so other texts can be seen
- Add more content 
- Add more functionality

NOTE:
This issue is assigned to Xavy06 but should be created by Karl Russel Gueco, due to inability to use git-bash.

**Comment by Xavy06** [comment]
Noted .]

**Comment by Xavy06** [comment]
Done pi, update style and html file
