### ISSUE TITLE
Main Website

### ISSUE THREAD

**Issue by Bindetta** [Bindetta/GROUP5_CASE_STUDY_GITHUB#9]
**This Main Docking page must contain the following:**

**Functionality:**
1. Must contain every website created by all collaborators.
2. Every website should be accessed with no issues/bugs
3. All navigations and content are shown accordingly.
**Design:**
1. Simple to Elegant design that matches the theme of the Portfolios
2. Colors should be complimentary.

**Comment by Bindetta** [comment]
Noted

**Comment by Xavy06** [comment]
Noted

**Comment by gabriellaxereil** [comment]
Noted!

**Comment by chantelle-dane** [comment]
Noted

**Comment by chantelle-dane** [comment]
Done

**Comment by gabriellaxereil** [comment]
Noted!
